import type { Metadata } from "next";
import { Cinzel } from "next/font/google";
import "./globals.css";
import Link from 'next/link';

const cinzel = Cinzel({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-roman",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${cinzel.variable} antialiased bg-black text-white`}>
        <header>
         <nav style={{ padding: '20px', borderBottom: '1px solid #555', marginBottom: '20px' }}>
  <Link href="/" style={{ marginRight: '20px', fontSize: '18px' }}>Home</Link>
  <Link href="/passage" style={{ marginRight: '20px', fontSize: '18px' }}>Passage</Link>
  <Link href="/birddoors" style={{ marginRight: '20px', fontSize: '18px' }}>Bird Doors</Link>
  <Link href="/forest" style={{ marginRight: '20px', fontSize: '18px' }}>Forest</Link>
  <Link href="/shore" style={{ marginRight: '20px', fontSize: '18px' }}>Shore</Link>
  <Link href="/hill" style={{ marginRight: '20px', fontSize: '18px' }}>Hill</Link>
  <Link href="/augury" style={{ marginRight: '20px', fontSize: '18px' }}>Augury</Link>
  <Link href="/swarmscape" style={{ marginRight: '20px', fontSize: '18px' }}>Swarmscape</Link>
  <Link href="/game" style={{ marginRight: '20px', fontSize: '18px' }}>Game</Link>
  <Link href="/game2" style={{ marginRight: '20px', fontSize: '18px' }}>Game 2</Link>
  <Link href="/game3" style={{ marginRight: '20px', fontSize: '18px' }}>Game 3</Link>
  <Link href="/relevance" style={{ marginRight: '20px', fontSize: '18px' }}>Relevance</Link>
  <Link href="/context" style={{ marginRight: '20px', fontSize: '18px' }}>Context</Link>
  <Link href="/docs" style={{ fontSize: '18px' }}>Documentation</Link>
</nav>
        </header>

        <main style={{ padding: '20px' }}>
          {children}
        </main>
      </body>
    </html>
  );
}