import type { Metadata } from "next";
import { Cinzel } from "next/font/google";
import "./globals.css";
import Link from 'next/link';
import { WebSocketProvider } from "@/contexts/WebSocketContext";
import { AuspicesProvider } from "@/contexts/AuspicesProvider";

const cinzel = Cinzel({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-roman",
});

export const metadata: Metadata = {
  title: "Templum",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <WebSocketProvider>
        <AuspicesProvider>
          <body className={`${cinzel.variable} antialiased bg-black text-white`}>
            <main>
              {children}
            </main>
          </body>
        </AuspicesProvider>
      </WebSocketProvider>
    </html>
  );
}
